### PR TITLE
Null safety migration

### PR DESCRIPTION
**Pull request by albertodev01**
Null safety migration work for the `math-espressions` package!

### CODE REVIEW

**Comment by fkleon** [comment]
Thanks for your contribution, could you please rebase this onto the new `null-safety` branch that I created? It has an updated pubspec and Travic CI config.

**Comment by IchordeDionysos** [comment]
@albertodev01 any updates on this one? ☺️

**Comment by IchordeDionysos** [comment]
Fixes #37

**Comment by fkleon** [comment]
Thanks for your contribution. Have cherry picked this into a new branch - see #45

**Pull request closed without merging**
